# Generated by Django 2.1.2 on 2019-05-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_area_professores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professores',
            name='area',
        ),
        migrations.AddField(
            model_name='area',
            name='professor',
            field=models.ManyToManyField(to='blog.Professores'),
        ),
    ]
